### ISSUE TITLE
[Suggestion] Add Chisel Support for "Timber Framed" blocks

### ISSUE THREAD

**Issue by starg09** [Alsender/Earthworks#1]
While the recipes on themselves sound like a good stand-alone method, it would be nice to be able to make a wall by placing a big wall of the same type, then cycle to the desired one on each spot by left clicking with a chisel. Maybe you could implement this?

Even when some of the blocks don't cycle with each other using your current recipes, I think the addition of this feature would benefit builders making use of your blocks :)

**Comment by Alsender** [comment]
There's 39 different designs per infill type. While I might be able to figure out how to make a hammer (those justsound better for changing the timber type, rathee than a chisel, right?) that can cycle through them in world, I feel like that would be a real pain in the ass if you liked the 39th block... 

And I would just like to say, I'm an just an artist pretending they're a mod developer. So I make no promises on anything I say I might be able to do.

**Comment by Barhandar** [comment]
If they mean Chisel as the mod, it firstly should be relatively easy, and secondly Chisel has an option to leave the block in the chisel tool and then chisel appropriate in-world blocks to it instead of cycling as usual.

**Comment by Alsender** [comment]
Two weeks down, and all I have for my efforts are a headache, and no working carpenters tools.  I takes a better mind than mine to figure this out.

**Comment by starg09** [comment]
Huh, shouldn't be that hard to implement the (non-required) Chisel integration. Never suggested having it as required, more like what Ztones had on 1.7 :P 

Maybe @drullkus or someone from the Chisel-Team can assist you?

**Comment by Alsender** [comment]
Problem is I don't know java. At all.  I followed tutorials to learn how to add basic blocks, and did some poking through other open source mods/minecraft source code to get this mod where it is now, but otherwise, even with assistance, I'm utterly useless.  No matter how much I try to poke through Chisel2's source, I can't really make much sense of what I have to do to integrate it.  Do you have a mod in mind that you're thinking of with chisel integration that I can look through?

**Comment by Drullkus** [comment]
I can try to help next week or so. I believe there something within IMC that you can do. I could just sumbit a PR too.
