### ISSUE TITLE
[1.11.2] Mirroring recipes conflicts with right facing recipes

### ISSUE THREAD

**Issue by Rosethorns** [Alsender/Earthworks#12]
Description:
Any recipe that can be horizontally mirrored currently overwrites their right handed counterpart. This can be seen easily with Lath and Plaster recipes. Mirroring on these recipes needs to be disabled.
Currently right facing recipes are impossible to craft because their left facing mirrors override them.

Recreate:
1. try to make a left frame lath and plaster wall. 3 timber on the left 3 plaster in the middle. Works correctly.
2. try to make a right frame lath and plaster wall. 3 timber on the right 3 plaster in the middle.
3. Outputs a left frame lath and plaster wall due to recipe mirroring.

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2252
Earthworks: 1.1.1

**Comment by Alsender** [comment]
Subconsciously, I knew that recipes mirrored...  Unfortunately that did not register at all when I set all those recipes.  I'll figure out a way to disable recipe mirroring...

**Comment by Alsender** [comment]
Fixed! Look for an update in a little bit!
