### ISSUE TITLE
I can craft Earthworks stairs for free in my inventory

### ISSUE THREAD

**Issue by PrinceOfAmber** [Alsender/Earthworks#14]
![earthworks infinite crafting](https://cloud.githubusercontent.com/assets/621529/24691642/a9c8a246-1989-11e7-851e-d6589950dcfc.PNG)

At first the crafting is normal.  But if i put something in my 2x2 and remove it, those stairs appear.  I can take them out for free.

**Comment by Alsender** [comment]
Is it any item in particular? I'm not getting the same results. I've tried a bunch of different common items, including those shown in your screen cap, but I'm not getting anything. Nor can I think of any reason why this would be happening either.

**Comment by erindalc** [comment]
I have a similar issue, I just updated to 1.3.0

![image](https://cloud.githubusercontent.com/assets/12499779/26536431/baff5618-4404-11e7-87c3-189bc1db0cf9.png)

**Comment by erindalc** [comment]
Also occurs with crafting tables:

![image](https://cloud.githubusercontent.com/assets/12499779/26536513/9f40066a-4405-11e7-928d-ad46c95f1b4c.png)

The Reed block

**Comment by Alsender** [comment]
I am again, going to need more information on this.  What recipe are you crafting right before this?  Does any recipe cause this, or is it just a specific one? What mods have you installed?

**Comment by erindalc** [comment]
No recipe. I just open the crafting table and this happens every time without fail. 

Mods:

![image](https://cloud.githubusercontent.com/assets/12499779/26560461/d1ca1cc2-4484-11e7-954d-bea188051ec6.png)

![image](https://cloud.githubusercontent.com/assets/12499779/26560468/d87bcf84-4484-11e7-9e75-23441f39ab4b.png)

**Comment by erindalc** [comment]
Forge version: 13.20.0.2309

**Comment by erindalc** [comment]
[EarthworksBug-1.0.zip](https://github.com/Alsender/Earthworks/files/1036545/EarthworksBug-1.0.zip)

There's the pack I'm using in a Curse export if you'd like to test it yourself.

**Comment by Alsender** [comment]
So, I'm trying to track this issue down, and I'm not entirely sure what is going on.  Its not a mod interaction, because after removing mods one by one, the issue persisted until only Earthworks remained....  After updating the mod to a newer version, the issue went away, however.  Perhaps the same happens for you?

**Comment by erindalc** [comment]
I'll give it a test in a couple hours with an updated version of Earthworks.

**Comment by erindalc** [comment]
Weirdly enough, I reinstalled the mod (Didn't touch the config), and the issue no longer persists.

**Comment by Alsender** [comment]
Yeah, I did the same exact thing and the issue went away as well. No clue what causes it.... At least it seems to be resolved for now...
