### ISSUE TITLE
Earthworks slabs don't make double slabs

### ISSUE THREAD

**Issue by Vazkii** [Alsender/Earthworks#17]
![2017-05-24_13 33 07](https://cloud.githubusercontent.com/assets/1794735/26403322/be2b92ac-4085-11e7-9cb6-c6394e79795c.png)

Earthworks slabs create a stack when placed on eachother rather than making a double slab, as one would expect.

Minecraft 1.11
Earthworks 1.2.3
Forge 2299

**Comment by Alsender** [comment]
Unfortunately this is on my low priority list.  It doesn't render the mod unplayable, and I've got a few changes and fixes in the pipeline that I want to get out first.
