### ISSUE TITLE
[Feature Request] Add a config for reducing/disabling chalk spawning in the world

### ISSUE THREAD

**Issue by starg09** [Alsender/Earthworks#2]
Some mod author may want to alter this, for various reasons like:

* Wanting to reduce it so it's as rare as the other mods' stones (e.g. Quark, Chisel, Railcraft, etc.)
* Wanting to remove the stone generation entirely, and replace it with a custom recipe for _reasons_ (Maybe other mod adding a different chalk that has oredict)

It would be nice to have a config which allowed the dev to set how rare this block will generate, or to disable it in its entirety.

**Comment by Alsender** [comment]
I will have to take a look into how to add config settings, though I think I should be able to.  I don't think I'll make a recipe to obtain chalk, because I had thought on that for quite a while and decided there was no *good* recipe, but I might add recipes that use other mods' limestones.

**Comment by Darkosto** [comment]
I also would like to request config access. I'm having to currently disable the mod because it's generating in dimensions that I would like it blacklisted from. Is this a possibility, please?

Thanks!

**Comment by Alsender** [comment]
I literally just finished it. Look for an update later tonight. What dimensions is chalk generating in? I'll have to look into how dimensions work, but maybe eventually I can force an overworld only spawn. Maybe.

**Comment by Barhandar** [comment]
>but I might add recipes that use other mods' limestones.

Not limestones, marble. Firstly, because marble is merely metamorphized chalk, and secondly, because Chisel's marble is already pretty much chalk anyway, "generic white stone" without marble's luster - and ditto for Quark's, except it also lacks texture variety.

**Comment by Alsender** [comment]
I'm going say no on that idea. Marble may be a metamorphic product of limestone, but I've never heard of it being used to replace lime in prehistoric times to make plaster or cement.  Sure it's used as an addative in Venetian plaster, but that's not the same as saying limestone == marble.

**Comment by Barhandar** [comment]
>but I've never heard of it being used to replace lime in prehistoric times to make plaster or cement

And you've heard about _chalk_ used for the same?..

**Comment by Alsender** [comment]
No, but Chalk is a limestone, not a derivative. And I know that you can easily make chalk from plaster. I compromised there because I have plans on the backburner for chalk dust, and didn't want to add both limestone and chalk.
