### ISSUE TITLE
[1.10.2 1.3.1] Purple/Green Slate variants not craftable

### ISSUE THREAD

**Issue by Lykrast** [Alsender/Earthworks#21]
Polished/shingles/slab/stairs/... variants of Purple and Green Slate don't have a crafting recipe, unlike Blue Slate variants.

On a related note, Blue Slate can still be crafted using Flint despite now spawning naturally (intended?).

**Comment by Alsender** [comment]
Ah, sorry 'bout that! I'll have a fix out in a few!  And yes, blue slate is still going to have a craftable recipe for now, just in case people don't retrogen their worlds, but still want slate.  Eventually the recipe will be phased out.
