### ISSUE TITLE
Carpenter Tools Not Working

### ISSUE THREAD

**Issue by Spazmunki13** [Alsender/Earthworks#26]
Hello, I posted on your Curseforge and you told me to come post here with more information.

I'm on Minecraft 1.10.2 currently using Forge 12.18.3.2185 and using Earthworks version 1.3.4.

I have quite a list of other mods installed as well not sure if any would interfere. And I just tried using ONLY Earthworks and shift-right-clicking with a Square in my hand on a Timber framed block, nothing happens.

**Comment by Alsender** [comment]
Told ya it'd get faster results.  Give it a little for the file to be approved on CurseForge.
