### ISSUE TITLE
Caught exception from Earthworks

### ISSUE THREAD

**Issue by Sunconure11** [Alsender/Earthworks#5]
http://pastebin.com/WKcHk529

I did disable the blocks that are covered by quark using the config settings, and lowered chalk spawn rates.

**Comment by Alsender** [comment]
Were you crafting something, and if so what?

**Comment by Sunconure11** [comment]
I was not, I was starting up MC when I was hit with this crash.

**Comment by Alsender** [comment]
What version of Minecraft are you running, and what is your mod list?

**Comment by Sunconure11** [comment]
This is effectively my mod list:

https://github.com/Sunconure11/compitum-magia-issues/issues/2

Forge version: 12.18.3.2221

**Comment by Alsender** [comment]
Right. So. Apparently 1.11.2 is more lax about empty crafting recipes than 1.10.2 is.  And I was doing all my testing in 1.11.2.  This ought to be fixed now.
