### ISSUE TITLE
[Request] Wicker-bound, log-bound, wire-bound gabions, HESCOs, fabric+infill blocks and panes

### ISSUE THREAD

**Issue by Barhandar** [Alsender/Earthworks#7]
I have a lot of places simply _begging_ for gabions of gravel or otherwise soil (aka dirt) constrained by external reinforcement, be it wiring or wicker, but I have neither artistic skill for texture nor patience for C&B.

**Comment by Alsender** [comment]
I'm envisioning something along [these](http://i65.servimg.com/u/f65/14/85/40/28/gabion10.jpg) lines.  It'd basically be the wicker texture with an open top and bottom and some shading along the edges to round it out.  Getting a wire-like texture, be it actual wire or wicker, would be such a pain in the ass to render in 16x

**Comment by Barhandar** [comment]
> It'd basically be the wicker texture with an open top and bottom and some shading along the edges to round it out.

Pretty much, and variations with missing wicker and the gravel visible through the holes. Or grass-like CTM, that is, topmost gabion getting the gravel visible at the top edge of the side, with gabions underneath it being full-wicker.
