### ISSUE TITLE
Chalk generation causes runaway chunk loading

### ISSUE THREAD

**Issue by mezz** [Alsender/Earthworks#8]
The chalk `WorldGenMinable` is set very large, 64 blocks, so it often spills over into unloaded chunks which causes them to load. This causes runaway chunk loading when many chunks are spilled into in a row.

Since you only have an 8 block buffer space before you reach a new chunk, and the radius of a worldgen blob is pretty large, the largest number of blocks that are "safe" is well below 64. 

Dirt, gravel, diorite, granite, and others use 33 as their maximum value so I think you should stick to that as a safe value. If you need more chalk you can call it twice as often or something like that.

**Comment by Alsender** [comment]
Huh, did not know that.  I'll get a hotfix up right away.  Thanks!  (p.s. love your mods!)

**Comment by mezz** [comment]
Cool! Thanks for the quick fix.
